//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MiscTestApplication.DataAdapter.Model
{
    public partial class MainEntity1
    {
        #region Primitive Properties
    
        public virtual long Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<SubEntity> SubEntities
        {
            get
            {
                if (_subEntities == null)
                {
                    var newCollection = new FixupCollection<SubEntity>();
                    newCollection.CollectionChanged += FixupSubEntities;
                    _subEntities = newCollection;
                }
                return _subEntities;
            }
            set
            {
                if (!ReferenceEquals(_subEntities, value))
                {
                    var previousValue = _subEntities as FixupCollection<SubEntity>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSubEntities;
                    }
                    _subEntities = value;
                    var newValue = value as FixupCollection<SubEntity>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSubEntities;
                    }
                }
            }
        }
        private ICollection<SubEntity> _subEntities;

        #endregion
        #region Association Fixup
    
        private void FixupSubEntities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SubEntity item in e.NewItems)
                {
                    item.MainEntity1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SubEntity item in e.OldItems)
                {
                    if (ReferenceEquals(item.MainEntity1, this))
                    {
                        item.MainEntity1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
