//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MiscTestApplication.DataAdapter.Model
{
    public partial class EntityModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=EntityModelContainer";
        public const string ContainerName = "EntityModelContainer";
    
        #region Constructors
    
        public EntityModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EntityModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EntityModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<MainEntity1> MainEntity1
        {
            get { return _mainEntity1  ?? (_mainEntity1 = CreateObjectSet<MainEntity1>("MainEntity1")); }
        }
        private ObjectSet<MainEntity1> _mainEntity1;
    
        public ObjectSet<SubEntity> SubEntities
        {
            get { return _subEntities  ?? (_subEntities = CreateObjectSet<SubEntity>("SubEntities")); }
        }
        private ObjectSet<SubEntity> _subEntities;

        #endregion
    }
}
